defaults: &defaults
  at: NULL
  lag: &defaultLag 1

RollingExuber:
 windows:
  - 50
  - 100
 workers: 4
 lag: *defaultLag
 at: NULL
 exuber_lag:
  - 1
  - 2

RollingForecasts:
 windows :
  - 252
 workers : 4
 lag : 1
 at : NULL
 na_pad: TRUE
 simplify: FALSE
 forecast_type: "autoarima"
 h: 10
