# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_of_resids_cpp <- function(x) {
    .Call('_finfeatures_sum_of_resids_cpp', PACKAGE = 'finfeatures', x)
}

r_squared_cpp <- function(x) {
    .Call('_finfeatures_r_squared_cpp', PACKAGE = 'finfeatures', x)
}

